volumes:
  dvwa:


networks:
  dvwa:


services:
  dvwa:
    build: .
    image: fengwenhua/dvwa:v2.3
    # Change `always` to `build` to build from local source
    pull_policy: build
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      - dvwa
    ports:
      # 这里修改端口映射
      - 81:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped
